version: '3.8'

services:
  bankapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=bankdb;User Id=postgres;Password=1234;
    depends_on:
      - db
    container_name: bank_web_api
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bankdb
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql_container
    restart: unless-stopped

volumes:
  db_data:
