version: '3.8'

services:
  bankapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bankdb;Username=postgres;Password=1234;
      - Jwt__Key=ThisIsASuperSecureKeyForHMACSHA512ThatIsAtLeast64CharactersLong1234567890
      - Jwt__Issuer=your_issuer
      - Jwt__Audience=your_audience
    depends_on:
      - db
    container_name: bank_web_api
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrongPassword123
      - POSTGRES_DB=bankdb
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql_container
    restart: unless-stopped

volumes:
  db_data: